version: "2.3"
services:
# /home/data_acquisition
    data_acquisition:
        build:
            context: ./data_acquisition
            dockerfile: Dockerfile
        network_mode: host
        volumes:
        - ./data_acquisition:/home/data_acquisition
        - ./dbData:/home/dbData
        tty: true
        command: python3 /home/data_acquisition/counting_changes.py
    client:
        build:
            context: ./rail-visualization
            dockerfile: Dockerfile
        network_mode: host
        environment:
            - CANVAS_WIDTH=1114
            - CANVAS_HEIGHT=396
            - ICON_SIZE=40
        depends_on:
            - node-server
        volumes:
        - ./rail-visualization:/home/rail-visualization
        - ./map:/home/map
 
  
    node-server:
        build:
            context: ./server
        expose:
            - 5500
        ports:
            - 5500:5500
        network_mode: "host"
        environment:
            - PORT=5500
        volumes:
            - ./server:/home/server
            - ./dbData:/home/dbData

    database:
        image: 'bitnami/mongodb'
        volumes: 
            - ./data:/data/db
        ports:
            - "27020:27017"
        tty: true
        restart: always